openapi: 3.0.3
info:
  title: Mini E-Commerce Products API
  version: 1.0.0
  description: Contract-first Products CRUD API (v1)

servers:
  - url: /api/v1

tags:
  - name: Products
    description: Product management

paths:
  /products:
    get:
      tags: [Products]
      summary: List products (paginated)
      operationId: listProducts
      parameters:
        - name: page
          in: query
          required: false
          description: Zero-based page index
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          required: false
          description: Page size
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: sort
          in: query
          required: false
          description: Sort format `field,asc|desc` (e.g. `createdAt,desc`)
          schema:
            type: string
            example: createdAt,desc
        - name: q
          in: query
          required: false
          description: Optional text search query (name/description)
          schema:
            type: string
            example: iphone
      responses:
        '200':
          description: Products retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPageResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags: [Products]
      summary: Create a product
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '201':
          description: Product created
          headers:
            Location:
              description: URL of the created resource
              schema:
                type: string
                example: /api/v1/products/prd_123
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict (e.g., duplicate SKU if enforced)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products/{id}:
    get:
      tags: [Products]
      summary: Get product by id
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: prd_123
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags: [Products]
      summary: Replace product (full update)
      operationId: replaceProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: prd_123
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequest'
      responses:
        '200':
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict (e.g., duplicate SKU if enforced)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      tags: [Products]
      summary: Update product (partial update)
      operationId: patchProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: prd_123
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchProductRequest'
      responses:
        '200':
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict (e.g., duplicate SKU if enforced)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags: [Products]
      summary: Delete product
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: prd_123
      responses:
        '204':
          description: Product deleted
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:

    # ---------- Core Models ----------
    Product:
      type: object
      required:
        - id
        - name
        - price
        - currency
        - inStock
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          example: prd_123
        sku:
          type: string
          description: Optional SKU (can be used for uniqueness if you want)
          example: SKU-IPH15-BLK
          nullable: true
        name:
          type: string
          minLength: 3
          maxLength: 120
          example: iPhone 15
        description:
          type: string
          maxLength: 2000
          nullable: true
          example: Latest Apple iPhone
        price:
          type: number
          format: double
          minimum: 0
          example: 999.99
        currency:
          type: string
          description: ISO 4217 currency code
          minLength: 3
          maxLength: 3
          example: USD
        inStock:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          example: "2026-01-26T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2026-01-26T10:30:00Z"

    # ---------- Requests ----------
    CreateProductRequest:
      type: object
      required:
        - name
        - price
        - currency
        - inStock
      properties:
        sku:
          type: string
          nullable: true
          example: SKU-IPH15-BLK
        name:
          type: string
          minLength: 3
          maxLength: 120
          example: iPhone 15
        description:
          type: string
          maxLength: 2000
          nullable: true
          example: Latest Apple iPhone
        price:
          type: number
          format: double
          minimum: 0
          example: 999.99
        currency:
          type: string
          minLength: 3
          maxLength: 3
          example: USD
        inStock:
          type: boolean
          example: true

    UpdateProductRequest:
      type: object
      required:
        - name
        - price
        - currency
        - inStock
      properties:
        sku:
          type: string
          nullable: true
          example: SKU-IPH15-BLK
        name:
          type: string
          minLength: 3
          maxLength: 120
          example: iPhone 15
        description:
          type: string
          maxLength: 2000
          nullable: true
          example: Latest Apple iPhone
        price:
          type: number
          format: double
          minimum: 0
          example: 999.99
        currency:
          type: string
          minLength: 3
          maxLength: 3
          example: USD
        inStock:
          type: boolean
          example: true

    PatchProductRequest:
      type: object
      description: All fields optional; only provided fields will be updated
      properties:
        sku:
          type: string
          nullable: true
          example: SKU-IPH15-BLK
        name:
          type: string
          minLength: 3
          maxLength: 120
          nullable: true
          example: iPhone 15
        description:
          type: string
          maxLength: 2000
          nullable: true
          example: Latest Apple iPhone
        price:
          type: number
          format: double
          minimum: 0
          nullable: true
          example: 999.99
        currency:
          type: string
          minLength: 3
          maxLength: 3
          nullable: true
          example: USD
        inStock:
          type: boolean
          nullable: true
          example: true
      additionalProperties: false

    # ---------- Responses ----------
    ProductResponse:
      type: object
      required: [product]
      properties:
        product:
          $ref: '#/components/schemas/Product'

    ProductPageResponse:
      type: object
      required:
        - items
        - page
        - size
        - totalElements
        - totalPages
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 10
        totalElements:
          type: integer
          example: 120
        totalPages:
          type: integer
          example: 12

    # ---------- Error ----------
    ErrorResponse:
      type: object
      required: [message]
      properties:
        message:
          type: string
          example: Validation failed
        details:
          type: array
          description: Optional list of field-level errors
          items:
            $ref: '#/components/schemas/ErrorDetail'
          nullable: true
        traceId:
          type: string
          description: Optional correlation/trace id for debugging
          nullable: true
          example: 5f2c3d8a8b2b4c1c

    ErrorDetail:
      type: object
      required: [field, message]
      properties:
        field:
          type: string
          example: name
        message:
          type: string
          example: must be at least 3 characters
